import test from 'node:test';
import assert from 'node:assert/strict';
import {SessionNotebook} from '../public/notebook.js';
const storage=()=>{const values=new Map();return {getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};};
const lesson={status:'answer',answer:'A generated explanation',knowledgeMode:'lecture',board:{title:'Lesson',steps:['One step'],equation:'v = fλ',diagram:[]},check:{question:'A check?',solution:'Reason'},citations:[{url:'https://www.youtube.com/watch?v=H5ygtkokVsI&t=455s',title:'Lecture',time:'07:35'}]};
test('reload restores bounded notebook for only the active student',()=>{const s=storage(),a=new SessionNotebook(s,'student-a'),b=new SessionNotebook(s,'student-b');a.save({latest:lesson,currentQuestion:'Why?',history:Array.from({length:12},(_,i)=>({role:i%2?'assistant':'user',content:String(i)}))});assert.equal(b.load(),null);const restored=a.load();assert.equal(restored.latest.board.equation,'v = fλ');assert.equal(restored.history.length,8);assert.equal(restored.currentQuestion,'Why?');a.clear();assert.equal(a.load(),null);});
test('corrupt or unavailable browser storage does not interrupt the lesson',()=>{const s=storage(),n=new SessionNotebook(s,'student-a');s.setItem(n.key,'{broken');assert.equal(n.load(),null);const unavailable=new SessionNotebook({getItem(){throw Error()},setItem(){throw Error()},removeItem(){throw Error()}},'student-a');assert.equal(unavailable.save({latest:lesson}),false);assert.equal(unavailable.load(),null);assert.doesNotThrow(()=>unavailable.clear());});
test('restored lecture links reject executable or unexpected URLs',()=>{const s=storage(),n=new SessionNotebook(s,'student-a');n.save({latest:{...lesson,citations:[{url:'javascript:alert(1)'},{url:'https://attacker.example/watch?v=abc'},...lesson.citations]}});assert.equal(n.load().latest.citations.length,1);});
test('corrupt restored geometry cannot give canvas a negative ellipse radius',()=>{const s=storage(),n=new SessionNotebook(s,'student-a');s.setItem(n.key,JSON.stringify({version:1,latest:{...lesson,board:{...lesson.board,diagram:[{type:'circle',x:900,y:-20,radius:-10},{type:'arc',radius:500,startAngle:-900,endAngle:999}]}}}));const diagram=n.load().latest.board.diagram;assert.equal(diagram[0].radius,0);assert.equal(diagram[0].x,100);assert.equal(diagram[0].y,0);assert.equal(diagram[1].radius,70);assert.equal(diagram[1].startAngle,-360);assert.equal(diagram[1].endAngle,360);});
